apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.policy.locked: "true"
  name: helloworld
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - args:
        - -msg=Ahoy
        image: quay.io/weaveworks/helloworld:master-9a16ff945b9e
        name: helloworld
        ports:
        - containerPort: 80
      - args:
        - -addr=:8080
        image: quay.io/weaveworks/sidecar:master-a000002
        name: sidecar
        ports:
        - containerPort: 8080
