---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: nginx
  namespace: flux-example
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1-alpine-perl
        ports:
        - containerPort: 80
