---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxd
  namespace: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxd
      annotations:
        prometheus.io.port: "3031"
    spec:
      containers:
      - name: fluxd
        image: weaveworks/fluxd
        imagePullPolicy: Never # must build manually
        ports:
        - containerPort: 3031
        args:
        - --token=local-test-token
        - --fluxsvc-address=ws://authfe.default.svc.cluster.local/api/flux
