---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxd
  namespace: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxd
      annotations:
        prometheus.io.port: "3031"
    spec:
      containers:
      - name: fluxd
        image: weaveworks/fluxd
        imagePullPolicy: Never # must build manually
        ports:
        - containerPort: 3031
        args:
        - --token=local-test-token
        - --connect=ws://authfe.default.svc.cluster.local/api/flux
        - --git-url=git@github.com:paulbellamy/flux-example.git
        - --git-key=/data/fluxd/secret/deploy.key
        - --memcached-hostname=memcached.fluxy.svc.cluster.local
        volumeMounts:
        - name: fluxd-key
          mountPath: /data/fluxd/secret
      volumes:
      - name: fluxd-key
        secret:
          secretName: fluxd-key
