---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxsvc
  namespace: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxsvc
    spec:
      volumes:
      - name: db-volume
        hostPath:
          path: /tmp/fluxdata
      containers:
      - name: fluxsvc
        image: weaveworks/fluxsvc
        imagePullPolicy: Never # must build manually
        volumeMounts:
        - mountPath: /fluxdata
          name: db-volume
        ports:
        - containerPort: 3030
        args:
        - --database-source=file:///fluxdata/flux.db
