---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxd
  namespace: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxd
    spec:
      containers:
      - name: fluxd
        image: weaveworks/fluxd
        imagePullPolicy: Never # must build manually
        args:
        - --token=y8pzox9iiuweebrh7jge9ggkfahsdxqm
        - --fluxsvc-address=ws://frontend.default.svc.cluster.local/api/flux
